### PR TITLE
Implement basic support for AArch64

### PR DESCRIPTION
**Pull request by L-as**
I am a beginner to Haskell, so please do tell me if my code is unidiomatic. In particular, is there any better way to handle unimplemented paths than `error "unimplemented"`?

### CODE REVIEW

**Comment by u2zv1wx** [comment]
Thank you for your pull request! I would be happy if you could:
- reformat the data declaration of `Arch` so that it matches with other existing data declarations
- sort the syscalls of AArch64 in `src/Data/Syscalls.hs` by their numbers
- insert a newline after `->` of `(OSDarwin, ArchAArch64) -> error "unimplemented"` in `src/Data/Syscall.hs` so that it matches with the existing cases.
- change the `error "unimplemented"` in `src/Data/Syscall.hs` to `Nothing`

As for `error "unimplemented"` in `src/Emit.hs`, you can take the following way: Firstly add a function `logError'` in `src/Data/Log.hs` as follows:
```
logError' :: T.Text -> Log
logError' text =
  (Nothing, LogLevelError, text)
```
Next, add a function `raiseError'` in `src/Data/Env.hs` as follows:
```
raiseError' :: T.Text -> WithEnv a
raiseError' text =
  throw $ Error [logError' text]
```
The `throw` here is the one of [Control.Exception.Safe](https://hackage.haskell.org/package/safe-exceptions-0.1.7.0/docs/Control-Exception-Safe.html). I think this approach is more idiomatic than `error`.

Then you can use this function to handle unimplemented paths:
```
raiseError' $ "unsupported target: " <> showOS targetOS <> " (" <> showArch targetArch <> ")"
```

**Comment by L-as** [comment]
Thanks for the feedback! I've implemented the changes (or at least tried to).

**Comment by u2zv1wx** [comment]
Looks good! Just one minor nitpicking: Could you please modify
```
    (OSDarwin, ArchAArch64)
      -> Nothing
```
into
```
    (OSDarwin, ArchAArch64) ->
      Nothing
```
?

**Comment by L-as** [comment]
Fixed! I misread what you wrote earlier.

**Comment by u2zv1wx** [comment]
Merged, thanks a lot!

**Pull request merged**
